import React, { createContext, useState, useContext } from 'react';

const LanguageContext = createContext();

export const translations = {
  zh: {
    please_pay_nt_3000_instructions: '1. 請於現場繳費 NT$ 3,000\\n2. 繳費後，管理員將確認並更新您的會員狀態\\n3. 確認後您將享有協會會員權益',
    absence_approved: '請假已核准',
    absence_pending: '請假待審核',
    absence_request_approved_successfully: '請假申請已核准',
    absence_request_submitted_successfully: '請假申請提交成功',
    absence_requests: '請假申請',
    action: '操作',
    actions: '操作',
    activate: '上架',
    active: '上架中',
    activities: '活動',
    activity_added_successfully: '活動添加成功',
    activity_cannot_exceed_12_hours: '活動時間不可超過 12 小時',
    activity_date: '活動日期',
    activity_management: '活動管理',
    activity_must_be_at_least_15_minutes_long: '活動時間至少需要 15 分鐘',
    activity_name: '活動名稱',
    add_activity: '添加活動',
    add_coupon: '添加優惠券',
    add_coupon_profile: '+ 新增優惠券模板',
    add_family_member: '新增家庭成員',
    add_host: '添加主辦人',
    add_line_and_register: '➕ 加入 LINE 並註冊',
    add_line_official_account: '➕ 加入 LINE 官方帳號',
    add_your_children: '添加您的孩子資料',
    adding: '⏳ 添加中...',
    after_registration_send_this_page: '註冊完成後，將此頁面的連結傳送給 LINE 官方帳號',
    after_registration_the_coupon_will_be_automaticall: '✨ 完成註冊後，優惠券將自動轉移到您的帳戶，無需再次掃描！',
    agenda: '議程：',
    all: '全部',
    amount_paid: '已付金額',
    amount_to_pay: '應付金額：',
    annual_fee: '年費',
    approve: '核准',
    approve_upgrade: '批准升級',
    approved: '✓ 已核准',
    approving: '核准中...',
    are_you_sure_you_want_to_delete: '確定要刪除嗎？',
    are_you_sure_you_want_to_delete_this_class_informa: '確定要刪除此課程資訊嗎？',
    are_you_sure_you_want_to_delete_this_coupon: '確定要刪除此優惠券嗎？',
    are_you_sure_you_want_to_delete_this_meeting: '確定要刪除此會議嗎？',
    are_you_sure_you_want_to_delete_this_will_affect_a: '確定要刪除嗎？此操作將影響所有使用此課程資訊的開課。',
    are_you_sure_you_want_to_reject_this_upgrade_reque: '確定要拒絕此升級請求嗎？',
    association_friend: '會友',
    association_management: '協會管理',
    association_meeting_management: '協會會議管理',
    association_meetings: '協會會議',
    association_member: '協會會員',
    association_members: '協會會員',
    attendance: '出席狀態',
    attendance_updated_successfully: '出席狀態更新成功',
    attended: '已出席',
    auto_claiming: '自動領取中...',
    automatically_claiming_your_coupon_please_wait: '正在自動為您領取優惠券，請稍候...',
    back_to_list: '← 返回列表',
    banner_image_optional: '宣傳圖片 (選填)',
    basic_information: '基本資訊',
    bio: '簡介',
    birth_date: '生日 *',
    board_of_directors: '董事會',
    cancel: '取消',
    cancelled: '已取消',
    cannot_attend: '無法出席',
    change_photo: '更換照片',
    choose_payment_method: '選擇付款方式',
    choose_payment_method_and_complete_upgrade: '選擇付款方式並完成升級',
    class: '課程',
    class_and_activity: '課程與活動',
    class_and_activity_management: '課程與活動管理',
    class_cannot_exceed_12_hours: '課程時間不可超過 12 小時',
    class_details: '課程詳情',
    class_hosted_successfully: '開課成功',
    class_info_deleted_successfully: '課程資訊刪除成功',
    class_info_updated_successfully: '課程資訊更新成功',
    class_management: '課程管理',
    class_must_be_at_least_15_minutes_long: '課程時間至少需要 15 分鐘',
    class_name: '課程名稱',
    classes: '課程',
    click: '點擊下方「加入 LINE」按鈕加入晨光國際少年團官方帳號',
    click_to_download_form: '點擊下載表格',
    close: '關閉',
    complete_registration: '完成註冊',
    completed: '已完成',
    contact_information: '聯絡資料',
    copied_to_clipboard: '已複製到剪貼簿',
    copy: '複製',
    cost: '金額：',
    coupon_added_successfully: '優惠券添加成功！',
    coupon_claimed_successfully: '優惠券領取成功！',
    coupon_deleted_successfully: '優惠券刪除成功',
    coupon_description: '優惠券描述',
    coupon_expired: '優惠券已過期',
    coupon_image: '優惠券圖片 *',
    coupon_information_profiles: '優惠券資訊模板',
    coupon_information_will_be_auto_filled_based_on_pr: '選擇後將自動填入優惠券資訊',
    coupon_listed: '優惠券上架成功！',
    coupon_management: '優惠券管理',
    coupon_name: '優惠券名稱 *',
    coupon_profile_created: '優惠券模板創建成功！',
    coupon_profile_details: '優惠券模板',
    coupon_selected: '已選擇優惠券：',
    coupon_store: '優惠券商店',
    coupon_type: '優惠券類型 *',
    coupons: '優惠券',
    coupons_can_only_be_shared_to_new_members_you_are_: '優惠券只能分享給新會員。您已經是會員了！',
    coupons_for_new_members_only: '優惠券僅供新會員',
    coupon_not_eligible: '您不符合領取資格',
    coupons_for_members_with_no_completed_classes: '優惠券只能分享給未修過課程的會員。您已完成課程，因此無法領取此優惠券。',
    coupons_for_sale: '販售優惠券',
    create: '建立',
    create_coupon_profile: '創建優惠券模板',
    create_coupon_templates_to_use_in: '創建優惠券模板，可在「販售優惠券」和「會員管理」中使用。體驗券將使用此處上傳的圖片，不再自動使用課程橫幅。',
    create_meeting: '+ 建立會議',
    create_new_meeting: '建立新會議',
    create_profile: '創建模板',
    created: '創建於 ',
    creating: '建立中...',
    credit_card: '💳 信用卡',
    credit_card_under_construction: '信用卡（施工中）',
    current_status: '目前狀態：',
    date: '日期：',
    days_left: '天後過期',
    deactivate: '下架',
    delete: '🗑️ 刪除',
    delete_failed: '刪除失敗',
    delete_member: '刪除會員',
    delete_this_listing: '確定要刪除此販售優惠券嗎？',
    delete_this_profile: '確定要刪除此模板嗎？',
    deleting: '⏳ 刪除中...',
    description: '描述：',
    discount: '折扣',
    discount_coupon: '折扣券',
    discount_percentage: '折扣百分比 (%) *',
    done: '完成',
    download_the_absence_form_template: '下載請假表範本',
    edit: '編輯',
    edit_class_information: '編輯課程資訊',
    edit_meeting: '編輯會議',
    edit_profile: '編輯個人資料',
    education: '學歷',
    eg_no_1_section_1_fuxing_s_rd_da: '例如：台北市大安區復興南路一段',
    eg_ntu_music_dept: '例如：台灣大學音樂系',
    eg_piano_vocal: '例如：鋼琴、聲樂',
    en_us: 'zh-TW',
    end_time_must_be_after_start_time: '結束時間必須晚於開始時間',
    english_name: '英文名',
    english_name_optional: '英文名（選填）',
    enrolled: '已報名',
    enrolled_date: '報名日期',
    enrolled_members: '已報名會員',
    enrollment_details: '報名詳情',
    enrollment_history: '報名記錄',
    enrollment_successful: '報名成功！',
    enrollments: '報名項目',
    enter_english_name: '輸入英文名',
    enter_name: '輸入姓名',
    enter_your_line_id: '輸入您的 LINE ID',
    expired: '已過期',
    expiry_date_optional: '有效期限（可選）',
    failed_to_generate_share_link: '生成分享連結失敗',
    failed_to_load: '載入失敗',
    failed_to_load_please_try_again: '載入失敗，請稍後再試',
    failed_to_upload_image: '圖片上傳失敗',
    family_members_optional: '家庭成員資訊（選填）',
    female: '女',
    filter_by_status: '篩選狀態',
    follow_the_instructions_in_line_messages_to_comple: '按照 LINE 訊息中的指示完成註冊',
    form: '請假表',
    free: '免費',
    free_trial_coupon: '免費（體驗券）',
    from: '來自：',
    gender: '性別',
    general_member: '一般會員',
    generating_share_link: '正在生成分享連結...',
    gift_redemption: '禮物兌換',
    go_to_my_profile: '前往我的資料',
    host_added_successfully: '主辦人添加成功',
    host_deleted_successfully: '主辦人刪除成功',
    host_details: '主辦人詳情',
    host_management: '主辦人管理',
    hours_must_be_between_0_23: '小時必須在 0-23 之間',
    how_to_claim: '📋 如何領取',
    i_shared_a_coupon_with_youn: '🎁 我分享了一張優惠券給你！\\n',
    image_size_cannot_exceed_5mb: '圖片大小不能超過 5MB',
    image_size_must_be_less_than_2mb: '圖片大小不能超過 2MB',
    image_uploaded_successfully: '圖片上傳成功',
    important_notice: '重要提醒',
    in_person: '實體會議',
    inactive: '已下架',
    initializing: '正在初始化...',
    invalid_coupon_link: '無效的優惠券連結',
    invalid_time_format: '時間格式不正確',
    item_not_found: '找不到項目',
    leave_empty_for_no_expiration: '留空表示永久有效',
    line_id: 'LINE ID',
    line_pay: 'LINE Pay',
    line_pay_under_construction: 'LINE Pay（施工中）',
    line_sdk_failed_to_load_please_refresh_the_page: 'LINE SDK 載入失敗，請重新整理頁面',
    list_coupon_for_sale: '上架販售優惠券',
    list_coupon_profiles_for_sale_members_can_purchase: '將優惠券模板上架販售，會員可在「我的優惠券」頁面購買',
    list_for_sale: '上架販售',
    listing_deleted: '販售優惠券刪除成功',
    loaded_successfully: '載入成功',
    loading: '⏳ 載入中...',
    location: '地點',
    login_successful: '登入成功',
    login_with_line: '使用 LINE 登入',
    logout: '登出',
    male: '男',
    mandatory_meeting: '強制參加會議',
    mandatory_members_must_attend_or_submit_absence_fo: '強制參加（會員必須出席或提交請假表）',
    map_failed_to_load_please_use_the_address_directly: '地圖載入失敗，請直接使用地址',
    map_preview: '地圖預覽',
    mark_paid: '標記已付',
    mark_unpaid: '標記未付',
    meeting_created_successfully: '會議建立成功',
    meeting_deleted_successfully: '會議已刪除',
    meeting_details: '會議詳情',
    meeting_location: '會議地點',
    meeting_status_updated_successfully: '會議狀態更新成功',
    meeting_type: '會議類型',
    meeting_updated_successfully: '會議更新成功',
    member_deleted_successfully: '會員刪除成功',
    member_details: '會員詳細資料',
    member_id: '會員編號',
    member_login: '會員登入',
    member_since: '成為會員日期：',
    member_statistics: '會員統計',
    member_type: '會員類型：',
    members_can_view_and_enroll_in_this_class_by_click: '會員可以在個人選單中點擊「課程與活動」來查看和報名此課程！',
    members_must_attend_or_submit_absence_form: '會員必須出席或提交請假表',
    membership: '會籍狀態',
    membership_info: '會員資訊',
    membership_status: '會籍狀態',
    membership_status_updated: '會籍狀態已更新',
    minutes_must_be_between_0_59: '分鐘必須在 0-59 之間',
    mobile_number: '手機號碼 *',
    my_owned_coupons: '📋 我擁有的優惠券',
    name: '名稱：',
    no_absence_requests_yet: '尚無請假申請',
    no_coupon_profiles_yet: '尚無優惠券模板',
    no_coupons_for_sale_yet: '尚無販售中的優惠券',
    no_coupons_for_this_member: '此會員尚無優惠券',
    no_coupons_yet: '尚無優惠券',
    no_enrolled_activities: '尚無報名活動',
    no_enrolled_classes: '尚無報名課程',
    no_enrollments_yet: '目前尚無會員報名',
    no_form: '無表格',
    no_meetings_yet: '尚無會議',
    no_members_registered_yet: '尚無成員報名',
    no_registered_meetings: '尚未報名任何會議',
    no_upcoming_meetings_available: '目前沒有可報名的會議',
    not_attended: '未出席',
    not_valid_for_this_class: '不適用此課程',
    off: '折扣',
    online_zoom: '線上會議 (Zoom)',
    or_share_this_link: '或使用此連結分享',
    original_price: '原價',
    paid: '已付款',
    pay_in_person: '💵 現場付款',
    payment: '付款狀態',
    payment_method: '付款方式：',
    payment_method_updated: '付款方式已更新',
    pending: '⏳ 待審核',
    pending_upgrade_request: '待處理升級請求',
    phone: '電話',
    please_complete_registration_before_claiming_the_c: '請先完成註冊才能領取優惠券。',
    please_enter_a_valid_quantity: '請輸入有效的數量',
    please_enter_a_valid_taiwan_phone_number_9_10_digi: '請輸入有效的台灣手機號碼（9-10位數字）',
    please_fill_in_all_required_fields: '請填寫所有必填欄位',
    please_fill_in_complete_time: '請填寫完整的時間',
    please_fill_required_fields: '請填寫必填欄位',
    please_follow_these_steps: '請按照以下步驟：',
    please_login_first: '請先登入',
    please_login_with_line_to_view_or_register_your_me: '請使用 LINE 帳號登入以查看或註冊您的會員資料',
    please_refresh_the_page_or_contact_administrator: '請重新整理頁面或聯繫管理員',
    please_remember_to_pay_at_the_venue: '請記得於課程現場繳費',
    please_save_this_information_and_show_it_on_the_cl: '請保存以下資訊，並於課程當天出示',
    please_select_a_class: '請選擇課程',
    please_select_a_coupon_profile: '請選擇優惠券模板',
    please_select_a_profile: '請選擇模板',
    please_show_this_confirmation_when_you_arrive_for_: '請於上課當天出示此確認資訊。您也可以在個人檔案的「我的課程」中查看報名記錄。',
    please_upload_an_image_file: '請上傳圖片文件',
    please_upload_the_absence_form: '請上傳請假表',
    points: '點',
    points_and_gifts: '點數與禮物',
    preview: '預覽：',
    price: '價格：$',
    price_ntd: '價格 (NTD) *',
    print_and_fill_out_the_form: '列印並填寫表格',
    processing: '⏳ 處理中...',
    profile_deleted: '模板刪除成功',
    profile_picture: '個人照片',
    profile_preview: '📋 模板預覽',
    purchase: '購買',
    purchase_coupons: '🛒 購買優惠券',
    purchase_failed: '購買失敗',
    purchase_successful: '購買成功！',
    purchasing: '⏳ 購買中...',
    quantity: '數量：',
    recipients_need_to_add_the_line_official_account_a: '💡 收件人必須尚未完成任何課程。優惠券將在他們完成註冊後自動加入帳戶。',
    redeem_coupon: '使用優惠券',
    referral_code_optional: '推薦碼（選填）',
    refresh_page: '重新整理',
    register: '報名',
    registered: '已報名人數',
    registered_meetings: '已報名會議',
    registered_members: '報名成員',
    registering: '報名中...',
    registration_failed: '報名失敗',
    registration_failed_please_try_again: '註冊失敗，請稍後再試',
    registration_required: '需要完成註冊',
    registration_successful: '註冊成功！',
    registration_time: '報名時間',
    reject: '拒絕',
    remaining: '剩餘：',
    remaining_uses: '剩餘使用次數：',
    reminder_coupons_can_only_be_shared_to_non_members: '提醒：優惠券只能分享給未修過課程的會員。已完成任何課程的會員無法領取分享的優惠券。',
    remove: '移除',
    remove_coupon: '移除優惠券',
    remove_image: '移除圖片',
    remove_member: '移除此成員',
    requested_at: '請求時間：',
    role: '角色：',
    role_updated: '角色已更新',
    save: '儲存',
    save_changes: '保存更改',
    saving: '儲存中...',
    scan_qr_code_to_claim: '掃描 QR Code 領取優惠券',
    scan_to_visit_claim_page_and_follow_instructions: '掃描後前往領取頁面，依照指示完成領取',
    select_class: '選擇課程 *',
    select_coupon: '選擇優惠券',
    select_coupon_profile: '選擇優惠券模板 *',
    select_host: '選擇主辦人',
    select_payment_method: '選擇付款方式',
    select_profile: '-- 選擇模板 --',
    send_line_announcement_to_all_association_members: '發送 LINE 公告給所有協會會員',
    send_line_announcement_to_all_line_followers: '發送 LINE 公告給所有 LINE 好友',
    session_expired_please_login_again: '登入失效，請重新登入',
    set_to_1_for_unlimited_stock: '設為 -1 表示無限庫存',
    share_coupon_to_new_friends: '分享優惠券給新朋友',
    share_to_new_friends: '分享給新朋友',
    share_via_line_to_new_friends: '透過 LINE 分享給新朋友',
    sold_out: '已售完',
    specialties: '專長',
    start_time_end_time: '開始時間 - 結束時間',
    status: '狀態：',
    status_updated: '狀態更新成功',
    status_updated_successfully: '狀態更新成功',
    stock: '庫存：',
    stock_quantity: '庫存數量',
    submission_failed: '提交失敗',
    submit: '提交',
    submit_absence_form: '提交請假表',
    submitted_at: '提交時間',
    submitting: '提交中...',
    supported_formats_jpg_png_max_5mb: '支援格式：JPG, PNG｜最大 5MB',
    system_configuration_error_missing_liff_id_please_: '系統設定錯誤 (缺少 LIFF ID)，請聯繫管理員',
    take_a_clear_photo_of_the_completed_form: '拍攝填妥表格的清晰照片',
    the_coupon_has_been_automatically_added_to_your_ac: '優惠券已自動加入您的帳戶。您可以在個人資料頁面查看所有優惠券。',
    this_coupon_can_be_used_for_a_trial: '此券可用於體驗',
    this_coupon_can_be_used_for_all_classes_with: '此券可用於所有課程，享',
    this_coupon_can_only_be_shared_with_friends_who_ha: '⚠️ 此優惠券僅能分享給尚未加入 LINE 官方帳號的朋友',
    this_coupon_or_share_link_has_expired: '此優惠券或分享連結已過期。',
    this_feature_is_currently_under_development_stay_t: '此功能正在開發中，敬請期待！',
    this_image_will_be_used_for_all_coupons_created_fr: '此圖片將用於所有使用此模板的優惠券（包括體驗券和折扣券）',
    time: '時間：',
    times: '次',
    tip_bookmark_this_page_to_easily_send_the_link_lat: '建議：將此頁面加入書籤，以便稍後傳送連結',
    trial: '體驗券',
    trial_coupon: '體驗券',
    trial_coupon_applied_free: '✓ 體驗券已使用（免費）',
    type: '類型',
    under_construction: '施工中',
    unpaid: '未付款',
    upcoming: '即將舉行',
    upcoming_meetings: '即將舉行的會議',
    update: '更新',
    update_failed: '更新失敗',
    update_successful: '更新成功',
    updating: '更新中...',
    upgrade_details: '升級詳情',
    upgrade_failed: '升級失敗',
    upgrade_fee: '升級費用',
    upgrade_request_approved: '升級請求已批准',
    upgrade_request_rejected: '升級請求已拒絕',
    upgrade_to: '升級至：',
    upgrade_to_association_member: '升級為協會會員',
    upgraded_on: '升級日期：',
    upload_banner_image_recommended_size_1000x600: '上傳橫幅圖片（建議尺寸 1000x600）',
    upload_form_photo: '上傳請假表照片',
    upload_image_max_2mb: '上傳圖片（最大 2MB）',
    upload_image_max_2mb_dimensions_must_be_500x300px: '上傳圖片（最大 2MB，尺寸必須：500x300px）',
    upload_image_recommended_size_1000x600px: '上傳圖片（建議尺寸：1000x600px）',
    upload_the_photo: '上傳照片',
    uploading: '上傳中...',
    used_up: '已用完',
    valid_for: '適用課程：',
    valid_until: '優惠券有效期至：',
    view: '查看',
    view_details: '查看',
    view_form: '查看表格',
    view_my_coupons: '查看我的優惠券',
    we_will_claim_the_coupon_for_you: '我們會為您領取優惠券！',
    welcome_please_fill_in_the_following_information_t: '歡迎！請填寫以下資料完成註冊',
    when_your_friend_joins_via_the_link_and_completes_: '當您的朋友透過連結完成註冊後，優惠券將自動加入他們的帳戶。朋友必須尚未完成任何課程才能領取。',
    year: '年',
    you_can_view_your_membership_status_in_your_profil: '您可以在個人檔案中查看會籍狀態。',
    you_don: '您目前沒有任何優惠券。請關注我們的活動以獲取優惠券！',
    you_have_no_available_coupons: '您目前沒有可用的優惠券',
    you_received_a_coupon: '您收到了優惠券！',
    you_will_immediately_enjoy_association_member_bene: '升級後將立即享有協會會員權益。請保存此確認資訊，並於現場出示繳費。',
    your_member_points: '您的會員點數',
    zoom_url: 'Zoom 連結',
    example_address_taipei: '例如：台北市大安區復興南路一段',
    click_add_line_account_button_below_to_add_our_official_account: '點擊下方「加入 LINE」按鈕加入晨光國際少年團官方帳號',
    add_your_children_information: '添加您的孩子資料',
    members_can_view_and_enroll_in_this_class_by_clicking_class_and_activity: '會員可以在個人選單中點擊「課程與活動」來查看和報名此課程！',
    after_registration_send_this_page_url_to_our_line_official_account: '註冊完成後，將此頁面的連結傳送給 LINE 官方帳號',
    you_don_t_have_any_coupons_yet_follow_our_events_to_get_coupons: '您目前沒有任何優惠券。請關注我們的活動以獲取優惠券！',
    create_coupon_templates_to_use_in_coupons_for_sale_and_member_management: '建立優惠券模板供「上架優惠券」和「團員管理」使用。體驗券將使用此處上傳的圖片，而不是課程橫幅。',
    this_coupon_can_only_be_shared_with_friends_who_havent_added_our_line_official_account_yet: '⚠️ 此優惠券僅能分享給尚未完成任何課程的會員',
    list_coupon_profiles_for_sale_members_can_purchase_in_my_coupons_section: '將優惠券模板上架販售，會員可在「我的優惠券」頁面購買',
    please_show_this_confirmation_when_you_arrive_for_class_you_can_also_view_your_enrollment_in_my_courses: '請於上課當天出示此確認資訊。您也可以在個人檔案的「我的課程」中查看報名記錄。',
    _add_coupon: '+ 添加優惠券',
    _add_family_member: '+ 新增家庭成員',
    _list_coupon_for_sale: '+ 上架優惠券',
    activityFull: '活動已滿',
    addClassInfo: '+ 新增課程資訊',
    addNew: '+ 新增',
    admin: '管理員',
    adminPanel: '管理面板',
    adminPanelTitle: '請使用管理員帳號登入',
    allClasses: '所有課程',
    appSubtitle: 'Sunrise Youth International',
    appTitle: '晨光國際少年團',
    availableActivities: '可報名活動',
    availableClasses: '可報名課程',
    back: '← 返回',
    banner: '橫幅圖片',
    bannerPreview: '橫幅預覽',
    birth_date_: '出生日期 *',
    birthDate: '出生日期',
    class_: '課程：',
    classDate: '課程日期',
    classInfo: '課程資訊',
    classInfoAddSuccess: '課程資訊添加成功',
    classInformation: '課程資訊',
    classFull: '課程已滿',
    defaultLoginCredentials: '如需登入帳號，請聯繫系統管理員',
    delete_: '刪除',
    discount_: '折扣：',
    englishAlias: '英文別名',
    enroll: '報名',
    enrollmentFailed: '報名失敗',
    error: '發生錯誤',
    familyMembers: '家庭成員',
    filterByClass: '依課程篩選',
    filterByDate: '依日期篩選',
    formPreview: '表格預覽',
    fullName: '姓名',
    host: '主辦人',
    hostBio: '主辦人簡介',
    hostClass: '主辦課程',
    hostEducation: '主辦人學歷',
    hostInfo: '主辦人資訊',
    hostSpecialties: '主辦人專長',
    invalidCredentials: '帳號或密碼不正確',
    language: 'zh',
    lineId: 'LINE ID',
    locationMap: '位置地圖',
    login: '登入',
    loginRequired: '請先登入',
    max: '最多',
    maxParticipants: '最多參與人數',
    member_since_: '成為協會會員日期',
    memberManagement: '會員管理',
    memberName: '會員姓名',
    mobile: '手機號碼',
    myProfile: '我的資料',
    name_: '姓名 *',
    noData: '無資料',
    participants: '人',
    password: '密碼',
    paymentStatusUpdated: '付款狀態已更新',
    preferNotToSay: '不公開',
    profile: '我的資料',
    qrCodeImage: 'QR Code',
    registeredActivities: '已報名活動',
    registeredClasses: '已報名課程',
    registered_: '已報名',
    selectFromCalendar: '從日曆選擇',
    status_: '狀態',
    teacherPreview: '主辦人圖片',
    username: '帳號',
    yourReferralCode: '您的推薦碼',
  },
  en: {
    please_pay_nt_3000_instructions: '1. Please pay NT$ 3,000 in person\\n2. After payment, admin will confirm and update your membership status\\n3. You will enjoy association member benefits after confirmation',
    absence_approved: 'Absence Approved',
    absence_pending: 'Absence Pending',
    absence_request_approved_successfully: 'Absence request approved successfully',
    absence_request_submitted_successfully: 'Absence request submitted successfully',
    absence_requests: 'Absence Requests',
    action: 'Action',
    actions: 'Actions',
    activate: 'Activate',
    active: 'Active',
    activities: 'Activities',
    activity_added_successfully: 'Activity added successfully',
    activity_cannot_exceed_12_hours: 'Activity cannot exceed 12 hours',
    activity_date: 'Activity Date',
    activity_must_be_at_least_15_minutes_long: 'Activity must be at least 15 minutes long',
    activity_name: 'Activity Name',
    add_activity: 'Add Activity',
    add_coupon: 'Add Coupon',
    add_coupon_profile: '+ Add Coupon Profile',
    add_family_member: 'Add Family Member',
    add_host: 'Add Host',
    add_line_and_register: '➕ Add LINE & Register',
    add_line_official_account: '➕ Add LINE Official Account',
    add_your_children: 'Add your children',
    adding: '⏳ Adding...',
    after_registration_send_this_page: 'After registration, send this page\\',
    after_registration_the_coupon_will_be_automaticall: '✨ After registration, the coupon will be automatically transferred to your account - no need to scan again!',
    agenda: 'Agenda:',
    all: 'All',
    amount_paid: 'Amount Paid',
    amount_to_pay: 'Amount to Pay: ',
    annual_fee: 'Annual Fee',
    approve: 'Approve',
    approve_upgrade: 'Approve Upgrade',
    approved: '✓ Approved',
    approving: 'Approving...',
    are_you_sure_you_want_to_delete: 'Are you sure you want to delete?',
    are_you_sure_you_want_to_delete_this_class_informa: 'Are you sure you want to delete this class information?',
    are_you_sure_you_want_to_delete_this_coupon: 'Are you sure you want to delete this coupon?',
    are_you_sure_you_want_to_delete_this_meeting: 'Are you sure you want to delete this meeting?',
    are_you_sure_you_want_to_delete_this_will_affect_a: 'Are you sure you want to delete? This will affect all classes using this info.',
    are_you_sure_you_want_to_reject_this_upgrade_reque: 'Are you sure you want to reject this upgrade request?',
    association_friend: 'Association Friend',
    association_management: 'Association Management',
    association_meeting_management: 'Association Meeting Management',
    association_meetings: 'Association Meetings',
    association_member: 'Association Member',
    association_members: 'Association Members',
    attendance: 'Attendance',
    attendance_updated_successfully: 'Attendance updated successfully',
    attended: 'Attended',
    auto_claiming: 'Auto-claiming...',
    automatically_claiming_your_coupon_please_wait: 'Automatically claiming your coupon, please wait...',
    back_to_list: '← Back to List',
    banner_image_optional: 'Banner Image (Optional)',
    basic_information: 'Basic Information',
    bio: 'Bio',
    birth_date: 'Birth Date *',
    board_of_directors: 'Board of Directors',
    cancel: 'Cancel',
    cancelled: 'Cancelled',
    cannot_attend: 'Cannot Attend',
    change_photo: 'Change Photo',
    choose_payment_method: 'Choose Payment Method',
    choose_payment_method_and_complete_upgrade: 'Choose payment method and complete upgrade',
    class: 'class',
    class_and_activity: 'Class & Activity',
    class_and_activity_management: 'Class & Activity Management',
    class_cannot_exceed_12_hours: 'Class cannot exceed 12 hours',
    class_details: 'Class Details',
    class_hosted_successfully: 'Class hosted successfully',
    class_info_deleted_successfully: 'Class info deleted successfully',
    class_info_updated_successfully: 'Class info updated successfully',
    class_must_be_at_least_15_minutes_long: 'Class must be at least 15 minutes long',
    class_name: 'Class Name',
    classes: 'Classes',
    click: 'Click ',
    click_to_download_form: 'Click to download form',
    close: 'Close',
    complete_registration: 'Complete Registration',
    completed: 'Completed',
    contact_information: 'Contact Information',
    copied_to_clipboard: 'Copied to clipboard',
    copy: 'Copy',
    cost: 'Cost: ',
    coupon_added_successfully: 'Coupon added successfully!',
    coupon_claimed_successfully: 'Coupon Claimed Successfully!',
    coupon_deleted_successfully: 'Coupon deleted successfully',
    coupon_description: 'Coupon Description',
    coupon_expired: 'Coupon Expired',
    coupon_image: 'Coupon Image *',
    coupon_information_profiles: 'Coupon Information Profiles',
    coupon_information_will_be_auto_filled_based_on_pr: 'Coupon information will be auto-filled based on profile',
    coupon_listed: 'Coupon listed!',
    coupon_management: 'Coupon Management',
    coupon_name: 'Coupon Name *',
    coupon_profile_created: 'Coupon profile created!',
    coupon_profile_details: 'Coupon Profile',
    coupon_selected: 'Coupon Selected: ',
    coupon_store: 'Coupon Store',
    coupon_type: 'Coupon Type *',
    coupons: 'Coupons',
    coupons_can_only_be_shared_to_new_members_you_are_: 'Coupons can only be shared to new members. You are already a member!',
    coupons_for_new_members_only: 'Coupons for New Members Only',
    coupon_not_eligible: 'You are not eligible to claim this coupon',
    coupons_for_members_with_no_completed_classes: 'Coupons can only be shared to members who have not completed any classes. You have completed classes and therefore cannot claim this coupon.',
    coupons_for_sale: 'Coupons For Sale',
    create: 'Create',
    create_coupon_profile: 'Create Coupon Profile',
    create_coupon_templates_to_use_in: 'Create coupon templates to use in ',
    create_meeting: '+ Create Meeting',
    create_new_meeting: 'Create New Meeting',
    create_profile: 'Create Profile',
    created: 'Created ',
    creating: 'Creating...',
    credit_card: '💳 Credit Card',
    credit_card_under_construction: 'Credit Card (Under Construction)',
    current_status: 'Current Status: ',
    date: 'Date:',
    days_left: 'days left',
    deactivate: 'Deactivate',
    delete: '🗑️ Delete',
    delete_failed: 'Delete failed',
    delete_member: 'Delete Member',
    delete_this_listing: 'Delete this listing?',
    delete_this_profile: 'Delete this profile?',
    deleting: '⏳ Deleting...',
    description: 'Description: ',
    discount: 'discount',
    discount_coupon: 'Discount Coupon',
    discount_percentage: 'Discount Percentage (%) *',
    done: 'Done',
    download_the_absence_form_template: 'Download the absence form template',
    edit: 'Edit',
    edit_class_information: 'Edit Class Information',
    edit_meeting: 'Edit Meeting',
    edit_profile: 'Edit Profile',
    education: 'Education',
    eg_no_1_section_1_fuxing_s_rd_da: 'e.g., No. 1, Section 1, Fuxing S Rd, Da\\',
    eg_ntu_music_dept: 'e.g., NTU Music Dept.',
    eg_piano_vocal: 'e.g., Piano, Vocal',
    en_us: 'en-US',
    end_time_must_be_after_start_time: 'End time must be after start time',
    english_name: 'English Name',
    english_name_optional: 'English Name (Optional)',
    enrolled: 'Enrolled',
    enrolled_date: 'Enrolled Date',
    enrolled_members: 'Enrolled Members',
    enrollment_details: 'Enrollment Details',
    enrollment_history: 'Enrollment History',
    enrollment_successful: 'Enrollment Successful!',
    enrollments: 'Enrollments',
    enter_english_name: 'Enter English name',
    enter_name: 'Enter name',
    enter_your_line_id: 'Enter your LINE ID',
    expired: 'Expired',
    expiry_date_optional: 'Expiry Date (Optional)',
    failed_to_generate_share_link: 'Failed to generate share link',
    failed_to_load: 'Failed to load',
    failed_to_load_please_try_again: 'Failed to load, please try again',
    failed_to_upload_image: 'Failed to upload image',
    family_members_optional: 'Family Members (Optional)',
    female: 'Female',
    filter_by_status: 'Filter by Status',
    follow_the_instructions_in_line_messages_to_comple: 'Follow the instructions in LINE messages to complete registration',
    form: 'Form',
    free: 'FREE',
    free_trial_coupon: 'Free (Trial Coupon)',
    from: 'From: ',
    gender: 'Gender',
    general_member: 'General Member',
    generating_share_link: 'Generating share link...',
    gift_redemption: 'Gift Redemption',
    go_to_my_profile: 'Go to My Profile',
    host_added_successfully: 'Host added successfully',
    host_deleted_successfully: 'Host deleted successfully',
    host_details: 'Host Details',
    host_management: 'Host Management',
    hours_must_be_between_0_23: 'Hours must be between 0-23',
    how_to_claim: '📋 How to Claim',
    i_shared_a_coupon_with_youn: '🎁 I shared a coupon with you!\\n',
    image_size_cannot_exceed_5mb: 'Image size cannot exceed 5MB',
    image_size_must_be_less_than_2mb: 'Image size must be less than 2MB',
    image_uploaded_successfully: 'Image uploaded successfully',
    important_notice: 'Important Notice',
    in_person: 'In Person',
    inactive: 'Inactive',
    initializing: 'Initializing...',
    invalid_coupon_link: 'Invalid coupon link',
    invalid_time_format: 'Invalid time format',
    item_not_found: 'Item not found',
    leave_empty_for_no_expiration: 'Leave empty for no expiration',
    line_id: 'LINE ID',
    line_pay: 'LINE Pay',
    line_pay_under_construction: 'LINE Pay (Under Construction)',
    line_sdk_failed_to_load_please_refresh_the_page: 'LINE SDK failed to load, please refresh the page',
    list_coupon_for_sale: 'List Coupon For Sale',
    list_coupon_profiles_for_sale_members_can_purchase: 'List coupon profiles for sale - members can purchase them in the ',
    list_for_sale: 'List For Sale',
    listing_deleted: 'Listing deleted',
    loaded_successfully: 'Loaded successfully',
    loading: '⏳ Loading...',
    location: 'Location',
    login_successful: 'Login successful',
    login_with_line: 'Login with LINE',
    logout: 'Logout',
    male: 'Male',
    mandatory_meeting: 'Mandatory Meeting',
    mandatory_members_must_attend_or_submit_absence_fo: 'Mandatory (members must attend or submit absence form)',
    map_failed_to_load_please_use_the_address_directly: 'Map failed to load, please use the address directly',
    map_preview: 'Map Preview',
    mark_paid: 'Mark Paid',
    mark_unpaid: 'Mark Unpaid',
    meeting_created_successfully: 'Meeting created successfully',
    meeting_deleted_successfully: 'Meeting deleted successfully',
    meeting_details: 'Meeting Details',
    meeting_location: 'Meeting location',
    meeting_status_updated_successfully: 'Meeting status updated successfully',
    meeting_type: 'Meeting Type',
    meeting_updated_successfully: 'Meeting updated successfully',
    member_deleted_successfully: 'Member deleted successfully',
    member_details: 'Member Details',
    member_id: 'Member ID',
    member_login: 'Member Login',
    member_since: 'Member Since: ',
    member_statistics: 'Member Statistics',
    member_type: 'Member Type:',
    members_can_view_and_enroll_in_this_class_by_click: 'Members can view and enroll in this class by clicking ',
    members_must_attend_or_submit_absence_form: 'Members must attend or submit absence form',
    membership: 'Membership',
    membership_info: 'Membership Info',
    membership_status: 'Membership Status',
    membership_status_updated: 'Membership status updated',
    minutes_must_be_between_0_59: 'Minutes must be between 0-59',
    mobile_number: 'Mobile Number *',
    my_owned_coupons: '📋 My Owned Coupons',
    name: 'Name: ',
    no_absence_requests_yet: 'No absence requests yet',
    no_coupon_profiles_yet: 'No coupon profiles yet',
    no_coupons_for_sale_yet: 'No coupons for sale yet',
    no_coupons_for_this_member: 'No coupons for this member',
    no_coupons_yet: 'No Coupons Yet',
    no_enrolled_activities: 'No enrolled activities',
    no_enrolled_classes: 'No enrolled classes',
    no_enrollments_yet: 'No enrollments yet',
    no_form: 'No form',
    no_meetings_yet: 'No meetings yet',
    no_members_registered_yet: 'No members registered yet',
    no_registered_meetings: 'No registered meetings',
    no_upcoming_meetings_available: 'No upcoming meetings available',
    not_attended: 'Not attended',
    not_valid_for_this_class: 'Not valid for this class',
    off: 'off',
    online_zoom: 'Online (Zoom)',
    or_share_this_link: 'Or Share This Link',
    original_price: 'Original Price',
    paid: 'Paid',
    pay_in_person: '💵 Pay in Person',
    payment: 'Payment',
    payment_method: 'Payment Method:',
    payment_method_updated: 'Payment method updated',
    pending: '⏳ Pending',
    pending_upgrade_request: 'Pending Upgrade Request',
    phone: 'Phone',
    please_complete_registration_before_claiming_the_c: 'Please complete registration before claiming the coupon.',
    please_enter_a_valid_quantity: 'Please enter a valid quantity',
    please_enter_a_valid_taiwan_phone_number_9_10_digi: 'Please enter a valid Taiwan phone number (9-10 digits)',
    please_fill_in_all_required_fields: 'Please fill in all required fields',
    please_fill_in_complete_time: 'Please fill in complete time',
    please_fill_required_fields: 'Please fill required fields',
    please_follow_these_steps: 'Please follow these steps:',
    please_login_first: 'Please login first',
    please_login_with_line_to_view_or_register_your_me: 'Please login with LINE to view or register your member profile',
    please_refresh_the_page_or_contact_administrator: 'Please refresh the page or contact administrator',
    please_remember_to_pay_at_the_venue: 'Please remember to pay at the venue',
    please_save_this_information_and_show_it_on_the_cl: 'Please save this information and show it on the class day',
    please_select_a_class: 'Please select a class',
    please_select_a_coupon_profile: 'Please select a coupon profile',
    please_select_a_profile: 'Please select a profile',
    please_show_this_confirmation_when_you_arrive_for_: 'Please show this confirmation when you arrive for class. You can also view your enrollment in ',
    please_upload_an_image_file: 'Please upload an image file',
    please_upload_the_absence_form: 'Please upload the absence form',
    points: 'points',
    points_and_gifts: 'Points & Gifts',
    preview: 'Preview:',
    price: 'Price: $',
    price_ntd: 'Price (NTD) *',
    print_and_fill_out_the_form: 'Print and fill out the form',
    processing: '⏳ Processing...',
    profile_deleted: 'Profile deleted',
    profile_picture: 'Profile Picture',
    profile_preview: '📋 Profile Preview',
    purchase: 'Purchase',
    purchase_coupons: '🛒 Purchase Coupons',
    purchase_failed: 'Purchase failed',
    purchase_successful: 'Purchase successful!',
    purchasing: '⏳ Purchasing...',
    quantity: 'Quantity: ',
    recipients_need_to_add_the_line_official_account_a: '💡 Recipients must not have completed any classes. The coupon will be automatically added to their account after registration.',
    redeem_coupon: 'Redeem Coupon',
    referral_code_optional: 'Referral Code (Optional)',
    refresh_page: 'Refresh Page',
    register: 'Register',
    registered: 'Registered',
    registered_meetings: 'Registered Meetings',
    registered_members: 'Registered Members',
    registering: 'Registering...',
    registration_failed: 'Registration failed',
    registration_failed_please_try_again: 'Registration failed, please try again',
    registration_required: 'Registration Required',
    registration_successful: 'Registration successful!',
    registration_time: 'Registration Time',
    reject: 'Reject',
    remaining: 'Remaining: ',
    remaining_uses: 'Remaining Uses: ',
    reminder_coupons_can_only_be_shared_to_non_members: 'Reminder: Coupons can only be shared to members who have not completed any classes. Members who have completed any classes cannot claim shared coupons.',
    remove: 'Remove',
    remove_coupon: 'Remove Coupon',
    remove_image: 'Remove Image',
    remove_member: 'Remove Member',
    requested_at: 'Requested At:',
    role: 'Role:',
    role_updated: 'Role updated',
    save: 'Save',
    save_changes: 'Save Changes',
    saving: 'Saving...',
    scan_qr_code_to_claim: 'Scan QR Code to Claim',
    scan_to_visit_claim_page_and_follow_instructions: 'Scan to visit claim page and follow instructions',
    select_class: 'Select Class *',
    select_coupon: 'Select Coupon',
    select_coupon_profile: 'Select Coupon Profile *',
    select_host: 'Select Host',
    select_payment_method: 'Select Payment Method',
    select_profile: '-- Select Profile --',
    send_line_announcement_to_all_association_members: 'Send LINE announcement to all association members',
    send_line_announcement_to_all_line_followers: 'Send LINE announcement to all LINE followers',
    session_expired_please_login_again: 'Session expired, please login again',
    set_to_1_for_unlimited_stock: 'Set to -1 for unlimited stock',
    share_coupon_to_new_friends: 'Share Coupon to New Friends',
    share_to_new_friends: 'Share to New Friends',
    share_via_line_to_new_friends: 'Share via LINE to New Friends',
    sold_out: 'Sold Out',
    specialties: 'Specialties',
    start_time_end_time: 'Start Time - End Time',
    status: 'Status:',
    status_updated: 'Status updated',
    status_updated_successfully: 'Status updated successfully',
    stock: 'Stock: ',
    stock_quantity: 'Stock Quantity',
    submission_failed: 'Submission failed',
    submit: 'Submit',
    submit_absence_form: 'Submit Absence Form',
    submitted_at: 'Submitted At',
    submitting: 'Submitting...',
    supported_formats_jpg_png_max_5mb: 'Supported formats: JPG, PNG | Max 5MB',
    system_configuration_error_missing_liff_id_please_: 'System configuration error (missing LIFF ID), please contact administrator',
    take_a_clear_photo_of_the_completed_form: 'Take a clear photo of the completed form',
    the_coupon_has_been_automatically_added_to_your_ac: 'The coupon has been automatically added to your account. You can view all your coupons in your profile page.',
    this_coupon_can_be_used_for_a_trial: 'This coupon can be used for a trial',
    this_coupon_can_be_used_for_all_classes_with: 'This coupon can be used for all classes with',
    this_coupon_can_only_be_shared_with_friends_who_ha: '⚠️ This coupon can only be shared with friends who haven\\',
    this_coupon_or_share_link_has_expired: 'This coupon or share link has expired.',
    this_feature_is_currently_under_development_stay_t: 'This feature is currently under development. Stay tuned!',
    this_image_will_be_used_for_all_coupons_created_fr: 'This image will be used for all coupons created from this profile (including trial and discount coupons)',
    time: 'Time:',
    times: 'times',
    tip_bookmark_this_page_to_easily_send_the_link_lat: 'Tip: Bookmark this page to easily send the link later',
    trial: 'Trial',
    trial_coupon: 'Trial Coupon',
    trial_coupon_applied_free: '✓ Trial Coupon Applied (Free)',
    type: 'Type',
    under_construction: 'Under Construction',
    unpaid: 'Unpaid',
    upcoming: 'Upcoming',
    upcoming_meetings: 'Upcoming Meetings',
    update: 'Update',
    update_failed: 'Update failed',
    update_successful: 'Update successful',
    updating: 'Updating...',
    upgrade_details: 'Upgrade Details',
    upgrade_failed: 'Upgrade failed',
    upgrade_fee: 'Upgrade Fee',
    upgrade_request_approved: 'Upgrade request approved',
    upgrade_request_rejected: 'Upgrade request rejected',
    upgrade_to: 'Upgrade To:',
    upgrade_to_association_member: 'Upgrade to Association Member',
    upgraded_on: 'Upgraded On: ',
    upload_banner_image_recommended_size_1000x600: 'Upload banner image (recommended size 1000x600)',
    upload_form_photo: 'Upload Form Photo',
    upload_image_max_2mb: 'Upload image (max 2MB)',
    upload_image_max_2mb_dimensions_must_be_500x300px: 'Upload image (max 2MB, dimensions must be: 500x300px)',
    upload_image_recommended_size_1000x600px: 'Upload image (recommended size: 1000x600px)',
    upload_the_photo: 'Upload the photo',
    uploading: 'Uploading...',
    used_up: 'Used Up',
    valid_for: 'Valid for: ',
    valid_until: 'Valid until: ',
    view: 'View',
    view_details: 'View',
    view_form: 'View Form',
    view_my_coupons: 'View My Coupons',
    we_will_claim_the_coupon_for_you: 'We will claim the coupon for you!',
    welcome_please_fill_in_the_following_information_t: 'Welcome! Please fill in the following information to complete registration',
    when_your_friend_joins_via_the_link_and_completes_: 'When your friend completes registration via the link, the coupon will be automatically added to their account. Friends must not have completed any classes to claim.',
    year: 'year',
    you_can_view_your_membership_status_in_your_profil: 'You can view your membership status in your profile.',
    you_don: 'You don\\',
    you_have_no_available_coupons: 'You have no available coupons',
    you_received_a_coupon: 'You Received a Coupon!',
    you_will_immediately_enjoy_association_member_bene: 'You will immediately enjoy association member benefits after upgrading. Please save this confirmation and show it when paying in person.',
    your_member_points: 'Your Member Points',
    zoom_url: 'Zoom URL',
    example_address_taipei: 'e.g., No. 1, Section 1, Fuxing S Rd, Da\'an District, Taipei City',
    click_add_line_account_button_below_to_add_our_official_account: 'Click "Add LINE Account" button below to add our official account',
    add_your_children_information: 'Add Your Children\'s information',
    members_can_view_and_enroll_in_this_class_by_clicking_class_and_activity: 'Members can view and enroll in this class by clicking "Class & Activity" in their profile menu!',
    after_registration_send_this_page_url_to_our_line_official_account: 'After registration, send this page\'s URL to our LINE Official Account',
    you_don_t_have_any_coupons_yet_follow_our_events_to_get_coupons: 'You don\'t have any coupons yet. Follow our events to get coupons!',
    create_coupon_templates_to_use_in_coupons_for_sale_and_member_management: 'Create coupon templates to use in "Coupons For Sale" and "Member Management". Trial coupons will use the image uploaded here instead of the class banner.',
    this_coupon_can_only_be_shared_with_friends_who_havent_added_our_line_official_account_yet: '⚠️ This coupon can only be shared with members who have not completed any classes',
    list_coupon_profiles_for_sale_members_can_purchase_in_my_coupons_section: 'List coupon profiles for sale - members can purchase in "My Coupons" section',
    please_show_this_confirmation_when_you_arrive_for_class_you_can_also_view_your_enrollment_in_my_courses: 'Please show this confirmation when you arrive for class. You can also view your enrollment in "My Courses" in your profile.',
    _add_coupon: '+ Add Coupon',
    _add_family_member: '+ Add Family Member',
    _list_coupon_for_sale: '+ List Coupon For Sale',
    activityFull: 'Activity Full',
    activity_management: 'Activity Management',
    addClassInfo: '+ Add Class Info',
    addNew: '+ Add New',
    admin: 'Admin',
    adminPanel: 'Admin Panel',
    adminPanelTitle: 'Please login with admin credentials',
    allClasses: 'All Classes',
    appSubtitle: '晨光國際少年團',
    appTitle: 'Sunrise Youth International',
    availableActivities: 'Available Activities',
    availableClasses: 'Available Classes',
    back: '← Back',
    banner: 'Banner',
    bannerPreview: 'Banner Preview',
    birth_date_: 'Birth Date *',
    birthDate: 'Birth Date',
    class_: 'Class: ',
    classDate: 'Class Date',
    classInfo: 'Class Info',
    classInfoAddSuccess: 'Class info added successfully',
    classInformation: 'Class Information',
    class_management: 'Class Management',
    classFull: 'Class Full',
    defaultLoginCredentials: 'Contact the system administrator for login credentials',
    delete_: 'Delete',
    discount_: 'Discount: ',
    englishAlias: 'English Alias',
    enroll: 'Enroll',
    enrollmentFailed: 'Enrollment failed',
    error: 'An error occurred',
    familyMembers: 'Family Members',
    filterByClass: 'Filter by Class',
    filterByDate: 'Filter by Date',
    formPreview: 'Form Preview',
    fullName: 'Full Name',
    host: 'Host',
    hostBio: 'Host Bio',
    hostClass: 'Host Class',
    hostEducation: 'Host Education',
    hostInfo: 'Host Info',
    hostSpecialties: 'Host Specialties',
    invalidCredentials: 'Invalid username or password',
    language: 'en',
    lineId: 'LINE ID',
    locationMap: 'Location Map',
    login: 'Login',
    loginRequired: 'Login required',
    max: 'Max',
    maxParticipants: 'Max Participants',
    member_since_: 'Member Since',
    memberManagement: 'Member Management',
    memberName: 'Member Name',
    mobile: 'Mobile',
    myProfile: 'My Profile',
    name_: 'Name *',
    noData: 'No data',
    participants: 'participants',
    password: 'Password',
    paymentStatusUpdated: 'Payment status updated',
    preferNotToSay: 'Prefer not to say',
    profile: 'My Profile',
    qrCodeImage: 'QR Code',
    registeredActivities: 'Registered Activities',
    registeredClasses: 'Registered Classes',
    registered_: 'Registered',
    selectFromCalendar: 'Select from calendar',
    status_: 'Status',
    teacherPreview: 'Host Photo',
    username: 'Username',
    yourReferralCode: 'Your Referral Code',
}
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState('zh'); // Default to Chinese

  const toggleLanguage = () => {
    setLanguage(prev => prev === 'zh' ? 'en' : 'zh');
  };

  const t = (key) => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, toggleLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};
